### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [Mika1212/PlanetSystem#1]
1. Не реализована возможность конфигурирования системы планет.
2. При симуляции нужно где-то указывать какие-то значения. Должно быть текущее время, относительно начала симуляции и должна быть возможность посмотреть координаты планет. Также, из информации в интерфейсе должно быть понятно, как расстояние между координатами переводится в реальное расстояние в км. 
3. Нет тестов.

**Comment by Mika1212** [comment]
Все исправил, осталось только тесты сделать

**Comment by Saloed** [comment]
1. С конфигурацией всё ещё проблемы:
* Нельзя добавить / удалить планету
* Нельзя задать стартовую позицию планеты (орбиту)
* Нельзя задать массу планеты
* Размер, который можно менять от 1 до 51 это странно. 1 чего? 51 чего? А если я хочу 200?
* С начальной скоростью планет, не понятно, почему их можно менять в процессе симуляции и в каких они единицах
2. Время лучше указывать в секундах
3. Попробуйте не делать это статическим полем [link](https://github.com/Mika1212/PlanetSystem/blob/d59e00f0c4130ad6b983b65c33b49ac54b4dbf0d/src/main/java/PlanetSystem.java#L15)
4. Нужно отделить логику, которая занимается симуляцией системы планет, от части, которая занимается визуализацией
5. По коду раскидано очень много каких-то констант. Надо гле-то их собрать и дать им имена
6. А зачем так делать? [link](https://github.com/Mika1212/PlanetSystem/blob/d59e00f0c4130ad6b983b65c33b49ac54b4dbf0d/src/main/java/PlanetSystem.java#L186)
7. Кажется, вы привязываете fps к скорости симуляции. Так лучше не делать.  Кажется, при высоком speed, картинка будет тормозить. Лучше рендерить кадры как получается, и просто смотреть сколько единиц реального времени прошло и двигать симуляцию уже в зависимости от этого времени.  [link](https://github.com/Mika1212/PlanetSystem/blob/d59e00f0c4130ad6b983b65c33b49ac54b4dbf0d/src/main/java/PlanetSystem.java#L438)
